"""
Django settings for Ecommerce project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from django.contrib.messages import constants as messages

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'v1m5uxl@=49a%ih4&2q#*%rjez1=8il0*k50mtk4ogn9ych3jf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
        'django.contrib.admin',
        'django.contrib.auth',
        'crispy_forms',
        'widget_tweaks',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'debug_toolbar',
        'livereload',
        'products',
        'search',
        'tags',
        'cart',
        'order',
        'accounts',
        'billing',
]

MIDDLEWARE = [
        'django.middleware.security.SecurityMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
        'livereload.middleware.LiveReloadScript',
        'debug_toolbar.middleware.DebugToolbarMiddleware'
]

ROOT_URLCONF = 'Ecommerce.urls'

INTERNAL_IPS = [
        '127.0.0.1',
]

TEMPLATES = [
        {
                'BACKEND': 'django.template.backends.django.DjangoTemplates',
                'DIRS': [
                        os.path.join(BASE_DIR, 'templates', 'base'),
                        os.path.join(BASE_DIR, 'templates', 'contact'),
                        os.path.join(BASE_DIR, 'accounts', 'templates', 'accounts'),
                        os.path.join(BASE_DIR, 'templates', 'about'),
                        os.path.join(BASE_DIR, 'templates', 'home'),
                        os.path.join(BASE_DIR, 'search', 'templates', 'search'),
                        os.path.join(BASE_DIR, 'cart', 'templates', 'cart'),
                        os.path.join(BASE_DIR, 'order', 'templates', 'order'),
                        os.path.join(BASE_DIR, 'billing', 'templates', 'billing')
                ],
                'APP_DIRS': True,
                'OPTIONS': {
                        'context_processors': [
                                'django.template.context_processors.debug',
                                'django.template.context_processors.request',
                                'django.contrib.auth.context_processors.auth',
                                'django.contrib.messages.context_processors.messages',
                                'django.template.context_processors.media'],
                },
        },
]

WSGI_APPLICATION = 'Ecommerce.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
        'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
        {
                'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
                'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
                'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
                'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
        os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "cdn", "static_root")

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, "cdn", "media_root")

MESSAGE_TAGS = {
        messages.SUCCESS: 'success',
        messages.ERROR: 'danger',
        messages.INFO: 'info',
        messages.WARNING: 'warning'
}

CRISPY_TEMPLATE_PACK = "bootstrap4"

AUTHENTICATION_BACKENDS = (
        'django.contrib.auth.backends.ModelBackend',
)

LOGOUT_REDIRECT_URL = '/login'
LOGIN_REDIRECT_URL = '/products'
LOGIN_URL = '/login'
